data: ./data/dataset_images
cnn_model: mobilenet_v2
num_epochs: 3
batch_size: 16
lrate: 0.0003
weight_decay: 0.00001
patience: 7
plot_loss_curve: true
seed: 0


# cnn models to be tested:
#   densenet121
#   densenet161
#   densenet169
#   densenet201
#   inception_v3
#   resnet18
#   resnet34
#   resnet50
#   resnet101
#   resnet152
#   vgg11
#   vgg13
#   vgg16
#   vgg19
#   alexnet
#   mobilenet_v2
